# Generated by Django 5.2.5 on 2025-09-01 21:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('image', models.FileField(upload_to='speciality')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PATIENT', 'Patient'), ('HEALTHCARE_PROVIDER', 'Healthcare Provider'), ('ADMIN_STAFF', 'Admin Staff'), ('SYSTEM_ADMIN', 'System Admin')], default='PATIENT', max_length=50, verbose_name='Type')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='HealthcareProvider',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='HealthcareProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='healthcare_providers')),
                ('education', models.TextField(blank=True, verbose_name='Education')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('about', models.TextField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=9)),
                ('address_line1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('license_number', models.CharField(max_length=100, verbose_name='License Number')),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_provider_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_provider', to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='AdminStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_staff_profile', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_staff', to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, verbose_name='Age')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Blood Type')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Chronic Conditions')),
                ('current_medications', models.TextField(blank=True, verbose_name='Current Medications')),
                ('insurance', models.CharField(blank=True, max_length=255, verbose_name='Insurance')),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in grams', null=True, verbose_name='Weight (kg)')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True, verbose_name='Height (cm)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderHospitalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_datetime_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.healthcareproviderprofile')),
            ],
            options={
                'unique_together': {('provider', 'hospital')},
            },
        ),
        migrations.AddField(
            model_name='healthcareproviderprofile',
            name='hospitals',
            field=models.ManyToManyField(through='api.ProviderHospitalAssignment', to='api.hospital'),
        ),
        migrations.AddField(
            model_name='healthcareproviderprofile',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_speciality', to='api.speciality'),
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime_utc', models.DateTimeField()),
                ('end_datetime_utc', models.DateTimeField()),
                ('healthcare_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='api.healthcareprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('healthcare_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='api.healthcareprovider')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField()),
                ('prescriptions', models.TextField()),
                ('healthcare_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.healthcareprovider')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='api.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_start_datetime_utc', models.DateTimeField()),
                ('appointment_end_datetime_utc', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='REQUESTED', max_length=20)),
                ('healthcare_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_appointments', to='api.healthcareprovider')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='api.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='healthcareproviderprofile',
            constraint=models.CheckConstraint(condition=models.Q(('years_of_experience__gte', 0)), name='experience_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='healthcareproviderprofile',
            constraint=models.CheckConstraint(condition=models.Q(('fees__gt', 0)), name='fees_above_0'),
        ),
        migrations.AddConstraint(
            model_name='healthcareproviderprofile',
            constraint=models.CheckConstraint(condition=models.Q(('license_number__regex', '^[A-Z0-9]{6,20}$')), name='valid_license_format'),
        ),
        migrations.AddConstraint(
            model_name='timeoff',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime_utc__gte', models.F('start_datetime_utc'))), name='timeoff_start_datetime_utc'),
        ),
        migrations.AlterUniqueTogether(
            name='timeoff',
            unique_together={('healthcare_provider', 'start_datetime_utc')},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('healthcare_provider', 'day_of_week')},
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('appointment_end_datetime_utc__gt', models.F('appointment_start_datetime_utc'))), name='appointment_end_datetime_utc_gt_start_datetime'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'healthcare_provider', 'appointment_start_datetime_utc')},
        ),
    ]
