# Generated by Django 5.2.4 on 2025-07-15 01:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('image', models.ImageField(upload_to='speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='doctors')),
                ('degree', models.CharField(max_length=100)),
                ('experience', models.DecimalField(decimal_places=2, max_digits=4)),
                ('about', models.TextField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=9)),
                ('address_line1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='api.speciality')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('experience__gte', 0)), name='experience_non_negative'), models.CheckConstraint(condition=models.Q(('fees__gt', 0)), name='fees_above_0')],
            },
        ),
    ]
