# Generated by Django 5.2.4 on 2025-08-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_speciality_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='San Diego', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='zip_code',
            field=models.CharField(default=91911, max_length=5),
            preserve_default=False,
        ),
    ]
