stages:
  - build-ci-image
  - lint-typecheck
  - test
  - build
  - trigger-vm

variables:
  REGISTRY: $CI_REGISTRY
  IMAGE_TAG_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
  IMAGE_TAG_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA

.default-python-job:
  image: python:3.11
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends make && rm -rf /var/lib/apt/lists/*
    - pip install poetry

.default-node-job:
  image: node:20-slim
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends make && rm -rf /var/lib/apt/lists/*

lint-frontend:
  stage: lint-typecheck
  extends: .default-node-job
  script:
    - cd frontend
    - npm ci
    - make -C .. ci-fe-lint
    - make -C .. ci-fe-type-check

lint-backend:
  stage: lint-typecheck
  extends: .default-python-job
  script:
    - cd backend
    - poetry install --with dev
    - make -C .. ci-be-lint
    - make -C .. ci-be-type-check

test-backend:
  stage: test
  image: docker:24
  services:
    - docker:dind
    - postgres:14
    - redis:7-alpine
  variables:
    POSTGRES_DB: docappoint_test
    POSTGRES_USER: postgres
    DJANGO_SECRET_KEY: test-secret-key
    POSTGRES_PASSWORD: password
    REDIS_URL: redis://redis:6379/0
    DJANGO_SETTINGS_MODULE: api.settings.development
  before_script:
    - apk add --no-cache make
  script:
    - make ci-be-dev-build
    - make ci-be-migrations-check-docker \
        POSTGRES_DB=$POSTGRES_DB \
        DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY \
        DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
    - make ci-be-run-migrations \
        POSTGRES_DB=$POSTGRES_DB \
        DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY \
        DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
    - make ci-be-test-docker

test-frontend:
  stage: test
  image: docker:24
  services:
    - docker:dind
  before_script:
    - apk add --no-cache nodejs npm make
  script:
    - npm ci
    - make ci-fe-test-run-docker

build-backend:
  stage: build
  extends: .default-python-job
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $IMAGE_TAG_BACKEND ./backend
    - docker push $IMAGE_TAG_BACKEND

build-frontend:
  stage: build
  extends: .default-node-job
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $IMAGE_TAG_FRONTEND ./frontend
    - docker push $IMAGE_TAG_FRONTEND

# trigger-vm:
#   stage: trigger-vm
#   script:
#     - curl -X POST https://us-central1-docappoint-devops.cloudfunctions.net/start-vm \
#       -H "Content-Type: application/json" \
#       -d "{\"commit\": \"$CI_COMMIT_SHA\", \"backend_image\": \"$IMAGE_TAG_BACKEND\", \"frontend_image\": \"$IMAGE_TAG_FRONTEND\"}"
#   only:
#     - main