[mypy]
python_version = 3.11
plugins = mypy_django_plugin.main
ignore_missing_imports = False
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False

[mypy.plugins.django-stubs]
django_settings_module = api.settings.base

# Third-party packages without stubs
[mypy-environ.*]
ignore_missing_imports = True

[mypy-rest_framework.*]
ignore_missing_imports = True

[mypy-rest_framework.test.*]
ignore_missing_imports = True

[mypy-rest_framework.decorators.*]
ignore_missing_imports = True

[mypy-rest_framework.permissions.*]
ignore_missing_imports = True

[mypy-rest_framework.response.*]
ignore_missing_imports = True

[mypy-rest_framework.views.*]
ignore_missing_imports = True

[mypy-rest_framework.routers.*]
ignore_missing_imports = True

[mypy-rest_framework.pagination.*]
ignore_missing_imports = True

[mypy-rest_framework.authentication.*]
ignore_missing_imports = True

[mypy-rest_framework.exceptions.*]
ignore_missing_imports = True

[mypy-django.*]
ignore_missing_imports = True

[mypy-django_ratelimit.*]
ignore_missing_imports = True

[mypy-django_cleanup.*]
ignore_missing_imports = True

[mypy-django_redis.*]
ignore_missing_imports = True

[mypy-django_cors_headers.*]
ignore_missing_imports = True

[mypy-django_filters.*]
ignore_missing_imports = True

[mypy-django_rest_passwordreset.*]
ignore_missing_imports = True

[mypy-djangorestframework_simplejwt.*]
ignore_missing_imports = True

# Your application
[mypy-api.models.*]
ignore_errors = True

[mypy-*.migrations.*]
ignore_errors = True

[mypy-api.management.commands.*]
ignore_errors = True